# Generated by Django 4.0.5 on 2022-11-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0004_user_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
    ]
