name: Create Issue Branch
on:
  issues:
    types: [assigned]
  pull_request:
    types: [closed]

jobs:
  create_branch:
    if: github.event.action == 'assigned'
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
  close_issue:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
